import Head from "next/head";
import PageLayout from "@app/layouts";
import { Pagination, PaginationProps, Table } from "antd";
import { columns } from "@app/contants/home";
import { useEffect, useState } from "react";
import { graphqlSetting } from "@app/graphql/home";
import { PageInfoTypes, TableDataType } from "@app/types/home";

export default function Home() {
  const [tableData, setTableData] = useState<Array<TableDataType>>();
  const [pageInfo, setPageInfo] = useState<PageInfoTypes>({
    currentPage: 0,
    hasNextPage: false,
    lastPage: 0,
    perPage: 0,
    total: 0,
  });
  const [page, setPage] = useState<number>(1);
  const [perView, setPerView] = useState<number>(5);
  const [loading, setLoading] = useState<boolean>(false);

  useEffect(() => {
    getData(page, perView);
  }, []);

  useEffect(() => {
    getData(page, perView);
  }, [page, perView]);

  const getData = async (page: number, perView: number) => {
    try {
      const setting = graphqlSetting(page, perView);
      setLoading(true);
      const res = await fetch(setting.url, setting.options);

      const data = await res.json();
      setTableData(
        data.data.Page.media.map((item: any) => ({
          id: item.id,
          romaji: item.title.romaji,
          english: item.title.english,
          native: item.title.native,
        }))
      );
      setPageInfo({
        ...data.data.Page.pageInfo,
        total:
          data.data.Page.pageInfo.total > 5000
            ? 5000
            : data.data.Page.pageInfo.total,
      });
      setLoading(false);
    } catch (error) {
      setLoading(false);
    }
  };

  const handlePagination: PaginationProps["onChange"] = (pageNumber) => {
    if (pageInfo.total > perView * (pageNumber - 1)) {
      setPage(pageNumber);
      getData(pageNumber, perView);
    }
  };

  const handleShowSizeChange: PaginationProps["onShowSizeChange"] = (
    current,
    pageSize
  ) => {
    setPerView(pageSize);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <Table
          columns={columns}
          dataSource={tableData}
          bordered
          pagination={false}
          loading={loading}
          scroll={{ y: "calc(100vh - 300px)" }}
        />
        <Pagination
          defaultCurrent={page}
          total={pageInfo.total}
          showSizeChanger
          defaultPageSize={5}
          pageSizeOptions={[5, 10, 20, 50, 100]}
          onShowSizeChange={handleShowSizeChange}
          className="home-pagination"
          onChange={handlePagination}
        />
      </PageLayout>
    </>
  );
}
